# Generated by Django 4.1.3 on 2023-12-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_appuser_patronymic_appuser_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='roles',
            new_name='role',
        ),
    ]
