# Generated by Django 4.1.3 on 2023-12-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LPProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers1_pay', models.IntegerField()),
                ('workers2_pay', models.IntegerField()),
                ('work_volume', models.IntegerField()),
                ('work_duration', models.IntegerField()),
                ('workers1_amount', models.IntegerField()),
                ('workers2_amount', models.IntegerField()),
            ],
        ),
    ]
