# Generated by Django 4.1.3 on 2023-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpproblem',
            name='workers1_pay',
            field=models.IntegerField(null=True),
        ),
    ]
