# Generated by Django 4.2.7 on 2023-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_lpproblem_work_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workers_pay', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='lpproblem',
            name='work_duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lpproblem',
            name='work_volume',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lpproblem',
            name='workers1_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lpproblem',
            name='workers1_pay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lpproblem',
            name='workers2_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lpproblem',
            name='workers2_pay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
