# Generated by Django 4.2.7 on 2023-12-29 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_lpproblemsolution_alter_lpproblem_work_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpproblemsolution',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.lpproblem'),
        ),
    ]
