# Generated by Django 4.2.7 on 2023-12-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_lpproblemsolution_workers_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lpproblemsolution',
            old_name='workers_amount',
            new_name='workers_by_days',
        ),
    ]
