# Generated by Django 4.2.7 on 2023-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_rename_workers_amount_lpproblemsolution_workers_by_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lpproblemsolution',
            name='workers_by_days',
        ),
        migrations.AddField(
            model_name='lpproblemsolution',
            name='workers_by_daysList',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
