# Generated by Django 4.1.3 on 2023-12-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_remove_lpproblemsolution_workers_by_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpproblem',
            name='min_workers1_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpproblem',
            name='min_workers2_amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
