# Generated by Django 4.1.3 on 2023-12-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_lpproblem_min_workers1_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpproblem',
            name='workers1_profession',
            field=models.CharField(default='Профессия 1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpproblem',
            name='workers2_profession',
            field=models.CharField(default='Профессия 2', max_length=50),
            preserve_default=False,
        ),
    ]
